name: Test PNPM Setup

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test_pnpm_versions:
    name: Test PNPM ${{ matrix.pnpm }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        pnpm: [9.15.5]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install PNPM ${{ matrix.pnpm }}
        run: npm install -g pnpm@${{ matrix.pnpm }}

      - name: Test: which pnpm/pnpx
        run: |
          pnpm -v
          pnpx -v

      - name: Test: pnpm install
        run: pnpm install

